### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by prvst** [bzhanglab/webgestaltpy#2]
Hello, can you please add a license file?

Thanks.

**Comment by iblacksand** [comment]
Sorry for the delay,

I will look into the appropriate license for this project, and let you know when it is added.

Best,
John

**Comment by prvst** [comment]
Thank you!

**Comment by prvst** [comment]
Hi, just checking in if there are any updates. We can't use your project if you don't have it properly licensed.
Thanks.

**Comment by iblacksand** [comment]
Sorry for the delay. We licensed the project under the GNU General Public License v3.0. The license was added in #3. We will push the changes to PyPI shortly.

**Comment by iblacksand** [comment]
webgestaltpy v0.3.1 has been pushed to PyPI with the license change. You can install the package with

```bash
pip install webgestaltpy
```

**Comment by prvst** [comment]
Thanks
